commerce_payment.commerce_payment_gateway.plugin.commerce_cryptocloud:
  type: commerce_payment_gateway_configuration
  mapping:
    api_key:
      type: string
      label: 'API key'
    shop_id:
      type: string
      label: 'Shop ID'
    secret_key:
      type: string
      label: 'Shop ID'
